# Generated by Django 3.1.1 on 2020-09-29 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_registered',
            field=models.DateField(default=''),
        ),
    ]
