# Generated by Django 3.1.1 on 2020-09-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200929_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
